---
title: "William Murphy, M.S., R.D.N."
output:
  html_document: default
  pdf_document: default
params:
  condensed: yes
css: custom-css.css
---

```{r setup, include=FALSE}
library(knitr); library(xtable); library(dplyr); library(ggplot2)
library(wordcloud)
knitr::opts_chunk$set(echo = F)
```

```{r data, include=FALSE}
contact <- read.csv("contact.csv", stringsAsFactors = F, header = F)
dat <- read.csv("resume-data.csv", stringsAsFactors = F) %>%
  #read table escapes the newline characters while reading them in, correct
  #this
  mutate_each(funs(gsub("\\n", "\n", ., fixed = T))) %>%
  # preserve ordering of groups by creating factors manually
  mutate_each(funs(factor(., levels = unique(.))), group, subgroup) %>%
  mutate(priority = as.numeric(priority))

```

```{r functions}
# renders tabular resume data
writeResumeTable <- function(table) {
  # skip over empty splits created for subgroup-group combos that don't exist
  if(nrow(table) < 1) return()

  subgroup = as.character(table$subgroup[1])
  if(subgroup != "")cat("\n### ", subgroup, "\n") else subgroup <- "nosubgroup"
  
  #sorting by the first 4-digit year while allowing for the field to display a
  #range of years or other text as well
  srt <- regmatches(table$date, regexpr("\\d{4}", table$date)) %>%
    as.numeric() %>%
    order(decreasing = T)
  table <- table[srt, ]
  # if there are text notes, move them onto their own row 
  if(max(nchar(table$text)) > 0) {
    origRows <- seq_len(nrow(table))
    textRows <- which(table$text != "")
    #duplicate the rows with text, then clear out other fields
    table <- table[c(origRows, textRows), ]
    table[origRows, "text"] <- ""
    table[seq(max(origRows) + 1, nrow(table)), 
          setdiff(names(table), c("text", "group", "subgroup"))] <- ""
    table <- table[order(c(origRows, textRows)), ]
  }
  
  # grabbing the output for modification before rendering
  htmlTable <- capture.output(
    table %>% select(-group, -subgroup, -priority) %>%
      xtable() %>%
      print(type = "html", include.rownames = F, include.colnames = F,
            html.table.attributes = paste0('id = "', gsub(" ", "", subgroup),
                                           '-table" class = "resume-table"'))
  )
  # for rows with the isolated text notes, expand that column to full
  # width of table via colspan attribute
  htmlTable <- paste(htmlTable, collapse = "\n")
  gsub("(<td>  </td> ){3}<td>(.*?)</td> <td>  </td>",
       "<td colspan = 5>\\2</td>", htmlTable) %>% 
    cat()
  
}


# renders text entries as <p> elements
writeResumeText <- function(dat) {
  if(nrow(dat) < 1) return()
  subgroup = as.character(dat$subgroup[1])
  if(subgroup != "")cat("\n### ", subgroup, "\n") else subgroup <- "none"
  dat$date <- as.Date(dat$date, format = "%m/%d/%Y")
  dat <- dat %>% arrange(desc(date))
  paste0('<p class="resume-text">', dat$text, "</p>\n") %>%
    cat()
}

# renders group heading, performs priority filtering, and calls appropriate
# renderers for the subgroups
resumeGroup <- function(x, type, header = T) {
  # hide rows without NA or 0 priority 
  # (unless the whole section has no marked priorites)
  x <- filter(
    x, 
    (!is.na(priority) & priority > 0) | all(is.na(priority)) |
      !params$condensed
  )
  # ensure some items remain after priority filtering to avoid printing
  # empty section headers
  if(nrow(x)) {
    if(header)cat("\n## ", as.character(x$group[1]), "\n")
    xList <- split(x, x$subgroup)
    if(type == "text") lapply(xList, writeResumeText) else
      lapply(xList, writeResumeTable)
  }
}  


```

```{r contact, results='asis'}
#subtitle
if(nrow(contact) > 1) {
  contact[2, ] %>%
    as.character() %>%
    `[`(!is.na(.) & . != "") %>%
    # instert divider symbol between each entry
    Reduce(f = function(a, b) append(a, " &#9672; ", b), 
           x = seq(1, (length(.) - 1) * 2, by = 2), init = .) %>%
    matrix(nrow = 1) %>%
    xtable() %>%
    print(type = "html", include.rownames = F, include.colnames = F,
          sanitize.text.function = eval,
          html.table.attributes = 
            'border=0 id="subtitle" class="header-table"')
}
# contact info ribbon below the name
contact[1, ] %>%
  `[`( , !is.na(.) & . != "") %>%
  xtable() %>%
  print(type = "html", include.rownames = F, include.colnames = F,
        html.table.attributes = 
          'border=1 id="contact-table" class="header-table"')

```

```{r tables, results='asis'}
# all tabular data
dat %>% filter(type == "table") %>%
  select(-type) %>%
  split(., .$group) %>%
  lapply(resumeGroup, type = "table") %>% 
  invisible()
```

```{r summary, results='asis', fig.height=.75, fig.width=7.5, fig.align='center'}
# summary chart
allEntries <- filter(dat, type == "text")
cat("\n## ", as.character(allEntries$group[1]), "\n")
plt <- ggplot(allEntries, aes(x = 1, fill = subgroup)) +
  geom_bar() + 
  # using the ..count.. variable created by stat = "count", we can calculate the
  # middle of the middle of each bar to align the labels
  geom_text(aes(y = sum(..count..) - cumsum(..count..) + ..count.. / 2, 
                label = ..count..), 
            stat = "count", size = 6) +
  #label the categories on alternating sides of the bars
  geom_text(aes(y = sum(..count..) - cumsum(..count..) + ..count.. / 2,
                label = subgroup, 
                x = ifelse(as.integer(subgroup) %% 2 == 0, 1.9, .1)),
            stat = "count", size = 3.5) +
  # tick marks for category labels
  geom_segment(aes(y = sum(..count..) - cumsum(..count..) + ..count.. / 2,
                   yend =  sum(..count..) - cumsum(..count..) + ..count.. / 2,
                   x = ifelse(as.integer(subgroup) %% 2 == 0, 1.45, .55),
                   xend = ifelse(as.integer(subgroup) %% 2 == 0, 1.6, .35)),
               stat = "count") +
  scale_fill_brewer(palette = "Dark2") +
  coord_flip(xlim = c(-.15,2)) +
  theme_classic() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        axis.title = element_blank(),
        legend.position = "none")
print(plt)

```

```{r results='asis'}
if(params$condensed) {
  cat('<p id="selected-items">Selected items (complete listing available at [wmurphyrd.github.io/resume](http://wmurphyrd.github.io/resume/)):</p>')
}
  
```

```{r clouds, fig.height=3, fig.width=3, warning=FALSE, results='asis', fig.pos='center', out.extra='class = "wordcloud"'}
# generate the wordcloud
wc <- dat %>% filter(type == "wordcloud") 
if(nrow(wc) > 1) {
  cat('\n<div class="wordcloudwrapper">',
      '<div class="wordcloudtextwrapper">',
      '<p class="wordcloud">',
      as.character(wc$subgroup[1]),
      '</p><span class="wordcloudalttext">Skills: ',
      paste(wc$title, collapse=", "),
      '</span></div>')
  wordcloud(wc$title, wc$priority, min.freq = 0, random.order = F, 
            colors = brewer.pal(pmin(8, length(unique(wc$priority))), "Dark2"),
            scale = c(1.5, .25))
  cat("</div>\n")
}
  
```

```{r texts, results='asis'}
# render the text entries
dat %>% filter(type == "text") %>%
  select(-type) %>%
  split(., .$group) %>%
  lapply(resumeGroup, type = "text", header = F) %>%
  invisible()
```


<p id="footer">Created with knitr. Source available at http://github.com/wmurphyrd/resume</p>
